DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'frog1_runtime') THEN
    CREATE ROLE frog1_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
END
$$;

GRANT frog1_runtime TO CURRENT_USER;
GRANT USAGE ON SCHEMA public TO frog1_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA public TO frog1_runtime;
GRANT USAGE, SELECT
  ON ALL SEQUENCES IN SCHEMA public TO frog1_runtime;
GRANT EXECUTE
  ON ALL FUNCTIONS IN SCHEMA public TO frog1_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO frog1_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO frog1_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO frog1_runtime;
